import rnastructure, pdb
from rnastructure.primary import fold

folder = fold.UNAfold()
seq = 'GAGGAGAACTTCTAGTGTATATTCTGTATACCTAATATTATAGCCTTTATCAACAATGGAATCCCAACAATTATCTCAACATTCCCCGATT-TTTCATGGTAGCGCCTGTGCTTCGGTTACTTCTAAAGAAGTCCAAACAACTCAAGATCCGTTAGACATTTCAGCTTCCAAAACAGAAGAATGTGAGAAGGTTTCCACTCAGGCTAATTCTCAACAGCCAACAACACCTCCCTCATCTGCTGTTCCAGAGAACCATCATCATGCCTCTCCTCAAGCTGCTCAAGTACCATTG-CCACAAAATGGGCCGTACCCACAGCAGCGCATGATGAATACCCAA---CAAGCCAATATTTCTGGCTGGCCAGTATACGGGCACCC-ATCCTTGATGCCGTATCCACCTTATCAAATGTCACCTATGTACGCTCCACCTGGGGCACAATCACAGTTTACACAATATCCACAATATGTTGGAACACATTTGAACACCCCGTCACCTGAGTCAGGTAATTCATTTCCTGATTCATC-CTCAGCAAAGTCTAA---TATGACATCCACTAATCAACATGTCAGACCACCGCCAATCTTAACCTCACCTAATGACTTTCTAAATTGGGTTAAAATATACATCAAATTTTTACAAAATTCGAATCTC'
seq = 'AAAAAAAAAAAAAAAAAAAAAA'

results = folder.fold(seq)

ils = results[0].loops(flanking=True)['internal']
hls = results[0].loops(flanking=True)['hairpin']

pdb.set_trace()

for loop in ils:
    print loop

for loop in hls:
    print loop
